SELECT *
FROM customer_data
LIMIT 5;

-- What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY gender;

-- Which customer used the discount but still spent more than average purchase amount
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data)

-- Which are the top 5 products with highest avg review rating
SELECT item_purchased, AVG(review_rating) as "Average Review Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer_data
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribe customers spend more? Compare avg spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) AS average_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;

-- Which 5 products have the highest percentage of purchases with discount_applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*), 2) as discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
   WHEN previous_purchases = 1 THEN 'NEW'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END as customer_segment
   FROM customer_data
)

SELECT customer_segment, count(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category
WITH item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER () OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_data
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP by subscription_status

-- What is the revenue contribution by age group
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC
